Updated README.md
sbplat/Macro-API pull request #13
Opened 2022-10-13 07:23 UTC by sb-decoder

# Description

I added How to Contribute Section and  contributors profile images into main readme file and fixed issue: #9 

Fixes #9 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (non-breaking change that updates the documentation)

# Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/sbplat/Macro-API/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/sbplat/Macro-API/blob/main/CODE_OF_CONDUCT.md)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-10-13 12:56 UTC, sbplat requested changes
Could you move the contributing guide over to `CONTRIBUTING.md` and make a hyperlink that links over to the `CONTRIBUTING.md` file

2022-10-13 12:59 UTC, sbplat commented on README.md
> +- Before Contribute Please read [CONTRIBUTING.md](https://github.com/sbplat/Macro-API/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/sbplat/Macro-API/blob/main/CODE_OF_CONDUCT
grammer

2022-10-13 13:00 UTC, sbplat commented on README.md
> +- Drop a :star: on the Github repository (optional)<br/>
I don't think line breaks (`br`) are necessary

2022-10-13 13:01 UTC, sbplat commented on README.md
> +- Create an issue of the project or a feature you would like to add in the project and get the task assigned for youself.(Issue can be any bug fixes or any feature you want to add in this project).
typo

2022-10-13 13:01 UTC, sbplat commented on README.md
> +## How to contribute:
`How to contribute:` should be changed to `Contributing` for consistency.
Could you also hyperlink this from the navigation links?

2022-10-13 17:12 UTC, sb-decoder commented
> Could you move the contributing guide over to `CONTRIBUTING.md` and make a hyperlink that links over to the `CONTRIBUTING.md` file

Please check correction and tell me if you want further changes.

2022-10-13 17:12 UTC, sb-decoder commented on README.md
> +- Drop a :star: on the Github repository (optional)<br/>
removed!

2022-10-13 20:29 UTC, sbplat commented
I made a few changes to both of the files. Is there anything that you want changed?

2022-10-14 05:03 UTC, sb-decoder commented
> I made a few changes to both of the files. Is there anything that you want to add?

No it's OK.

2022-10-14 12:46 UTC, sbplat commented
Thanks!

2022-10-14 12:46 UTC, merged