Fix move absolute on win32
sbplat/Macro-API pull request #44
Opened 2022-10-26 21:54 UTC by starsaminf

# Description

For solved this bug
it's necessary to get the **ScreenSize.Width** and **ScreenSize.Height**
This post helped me to resolve the bug

[how-to-calculate-coordinates-to-move-the-mouse-cursor-programmatically](https://stackoverflow.com/questions/21965353/how-to-calculate-coordinates-to-move-the-mouse-cursor-programmatically
)

The scale formula is 
```
x = p.X * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES)
y = p.Y * 65535 / GetDeviceCaps(GetDC(NULL), VERTRES)
```

## Type of change

- [ x ] Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?

As you can see, it requires **scaling**, so we are likely to have a small rounding error of +1 or -1.

2022-10-26 23:06 UTC, sbplat requested changes

2022-10-26 23:06 UTC, sbplat commented on src/win32/mouse.cpp
> +    x = x * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES);
As there is a +1 or -1 rounding error, this should be converted to a float or double and rounded (`std::round`).

2022-10-26 23:06 UTC, sbplat commented on src/win32/mouse.cpp
> +    x = x * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES);
It looks like `GetDC` and `GetDeviceCaps` will be called every time `MoveAbsolute` is called.

Could the screen size (width and height values) be cached in the `_Context` class?
The `_Context` class is defined in `src/internal.h` and the win32 implementation is in `src/win32/context.cpp`.

2022-10-26 23:11 UTC, sbplat commented
Thanks for the PR! Caching the values isn't necessary, but it's nice to have.

2022-10-27 02:54 UTC, starsaminf commented
> Thanks for the PR! Caching the values isn't necessary, but it's nice to have.

Thanks for your comments, I updated the code.

2022-10-27 23:21 UTC, sbplat commented
> > Thanks for the PR! Caching the values isn't necessary, but it's nice to have.
> 
> Thanks for your comments, I updated the code.

I will take a look right now.

2022-10-27 23:25 UTC, sbplat requested changes

2022-10-27 23:25 UTC, sbplat commented on src/win32/mouse.cpp
> +    input.mi.dx = round(x * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES));
An integer divided by an integer results in an integer. One possible solution is to use `65535.0` instead of `65535`.

2022-10-27 23:32 UTC, sbplat commented
Could you also update the move example (`examples/move.cpp`)? It's calling `MoveAbsolute` with `30000` right now and it should be reduced to a smaller number like `200`.

2022-10-29 15:42 UTC, sbplat approved these changes
LGTM, thanks!

2022-10-29 16:02 UTC, merged